git/urls.py
from django.conf.urls import url

from git import views

urlpatterns = [
    # /
    url(r'^$', views.index, name='repositories'),
    # /repository/add/
    url(r'^repository/add$', views.add, name='add_repository'),
    url(r'^repository/(?P<id>\d+)/remove$', views.remove, name='remove_repository'),
]

graph/urls.py
from django.conf.urls import url

from graph import views

urlpatterns = [
    # /graph/
    url(r'^$', views.index, name='graphs'),
    # /graph/:graphtype/
    url(r'^(?P<graph_type>[0-9]+)/$', views.detail, name='graph'),
]

pygitalyzer/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

import graph.urls
import repo.urls

urlpatterns = [
    url(r'^', include(repo.urls, namespace="repo")),
    url(r'^admin/', admin.site.urls),
    url(r'^graph/', include(graph.urls, namespace="graph")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

repo/urls.py
from django.conf.urls import url

from repo import views

urlpatterns = [
    # /
    url(r'^$', views.index, name='repositories'),
    # /repository/add/
    url(r'^repository/add$', views.add, name='add_repository'),
    url(r'^repository/(?P<id>\d+)/remove$', views.remove, name='remove_repository'),
]

git/models.py
from django.db import models


class Repository(models.Model):
    url = models.URLField(verbose_name="Repository Clone URL", unique=True)
    name = models.CharField(max_length=120, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name

repo/models.py
from __future__ import absolute_import
from os.path import join

from django.db import models
from git import Repo
from pygitalyzer.settings import BASE_DIR


class Repository(models.Model):
    url = models.URLField(verbose_name="Repository Clone URL", unique=True)
    name = models.CharField(max_length=120, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name

    def get_local_repo_dir(self):
        return join(BASE_DIR, 'tmp', 'repo', str(self.id))

    def init_repo(self):
        if hasattr(self, 'repo'):
            self.repo = Repo.init(self.get_local_repo_dir())
            self.origin = self.repo.create_remote('origin', self.url)

    def checkout(self):
        self.init_repo()
        print("Initializing repository")
        self.origin.fetch()
        print("Pulling from remote url")
        self.origin.pull(self.origin.refs[0].remote_head)
        print("Done")

git/forms.py
from django import forms

from git.models import Repository


class RepositoryForm(forms.ModelForm):
    class Meta:
        model = Repository
        fields = ['url', 'name']

repo/forms.py
from django import forms

from repo.models import Repository


class RepositoryForm(forms.ModelForm):
    class Meta:
        model = Repository
        fields = ['url', 'name']

git/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_safe

from git.models import Repository
from .forms import RepositoryForm


@require_safe
def index(request):
    context = {
        'form': RepositoryForm(),
        'repositories': Repository.objects.all(),
    }
    return render(request, "git/index.html", context)


@require_POST
def add(request):
    form = RepositoryForm(request.POST)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.full_clean()
        instance.save()

    return redirect("git:repositories")


@require_safe
def remove(request, id=None):
    repository = get_object_or_404(Repository, id=id)
    repository.delete()
    messages.success(request, "Successfully deleted")
    return redirect("git:repositories")

graph/views.py
from django.shortcuts import render


def index(request):
    return render(request, "graph/index.html", {})


def detail(request, graph_type):
    return render(request, "graph/detail.html", {})

pygitalyzer/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html", {})

repo/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_safe

from repo.models import Repository
from .forms import RepositoryForm


@require_safe
def index(request):
    context = {
        'form': RepositoryForm(),
        'repositories': Repository.objects.all(),
    }
    return render(request, "repo/index.html", context)


@require_POST
def add(request):
    form = RepositoryForm(request.POST)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.full_clean()
        instance.save()

    return redirect("repo:repositories")


@require_safe
def remove(request, id=None):
    repository = get_object_or_404(Repository, id=id)
    repository.delete()
    messages.success(request, "Successfully deleted")
    return redirect("repo:repositories")

git/templates/git/index.html
{% extends "index.html" %}

{% block title %}Repo Overview |{% endblock %}

{% block head %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('.modal-trigger').leanModal();
        });
    </script>
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="teal-text text-accent-1">Repositories</h1>

        <div class="row repositories">
            {% for repo in repositories %}
                <div class="col s6">
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title">{{ repo.name }}</span>
                        </div>
                        <div class="card-action">
                            <a href="{% url 'graph:graphs' %}" class="teal-text text-darken-1">Show Graphs</a>
                            <a href="{% url 'git:remove_repository' id=repo.id %}" class="teal-text text-darken-1">Delete</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div id="addRepoModal" class="modal">
            <form method="post" action="{% url 'git:add_repository' %}">{% csrf_token %}
                <div class="modal-content">
                    <h3>Create a new Repository</h3>
                    {{ form.as_p }}
                </div>
                <div class="modal-footer">
                    <button class="btn-flat waves-effect waves-red modal-action modal-close" name="cancel">Cancel</button>
                    <button class="btn-flat waves-effect waves-light modal-action" type="submit" name="create">Create</button>
                </div>
            </form>
        </div>
    </div>

    <div class="fixed-action-btn" style="bottom: 45px; right: 45px;">
        <a class="btn-floating btn-large waves-effect waves-light red right modal-trigger" href="#addRepoModal">
            <i class="material-icons">add</i>
        </a>
    </div>
{% endblock %}

graph/templates/graph/detail.html
{% extends "index.html" %}
{% load static from staticfiles %}

{% block title %}Graph Detail |{% endblock %}

{% block head %}
    <script type="text/javascript" src="{% static 'libs/d3/3.5.16/d3.min.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="white-text">Graph Detail</h1>
    </div>
{% endblock %}

graph/templates/graph/index.html
{% extends "index.html" %}

{% block title %}Graph Overview |{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="white-text">Graph Overview</h1>
    </div>
{% endblock %}

pygitalyzer/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %} PyGitalyzer</title>

        <link rel="icon" type="image/ico" href="{% static 'img/favicon.png' %}"/>

        <link rel="stylesheet" href="{% static 'libs/materialize/0.97.5/css/materialize.min.css' %}" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

        <script type="text/javascript" src="{% static 'libs/jquery/2.2.1/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'libs/materialize/0.97.5/js/materialize.min.js' %}"></script>
        {% block head %}
        {% endblock %}
    </head>
    <body class="blue-grey darken-4">
        <header>
            <nav class="top-nav blue-grey darken-2">
                <div class="container">
                    <div class="nav-wrapper">
                        <a class="brand-logo center" href="/"><img src="{% static 'img/favicon.png' %}" style="width: 26px; height: 36px; padding-top: 10px;" /> GITALYZER</a>
                    </div>
                </div>
            </nav>
        </header>
        {% block content %}{% endblock %}
    </body>
</html>

repo/templates/repo/index.html
{% extends "index.html" %}

{% block title %}Repo Overview |{% endblock %}

{% block head %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('.modal-trigger').leanModal();
        });
    </script>
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="teal-text text-accent-1">Repositories</h1>

        <div class="row repositories">
            {% for repo in repositories %}
                <div class="col s6">
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title">{{ repo.name }}</span>
                        </div>
                        <div class="card-action">
                            <a href="{% url 'graph:graphs' %}" class="teal-text text-darken-1">Show Graphs</a>
                            <a href="{% url 'repo:remove_repository' id=repo.id %}" class="teal-text text-darken-1">Delete</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div id="addRepoModal" class="modal">
            <form method="post" action="{% url 'repo:add_repository' %}">{% csrf_token %}
                <div class="modal-content">
                    <h3>Create a new Repository</h3>
                    {{ form.as_p }}
                </div>
                <div class="modal-footer">
                    <button class="btn-flat waves-effect waves-red modal-action modal-close" name="cancel">Cancel</button>
                    <button class="btn-flat waves-effect waves-light modal-action" type="submit" name="create">Create</button>
                </div>
            </form>
        </div>
    </div>

    <div class="fixed-action-btn" style="bottom: 45px; right: 45px;">
        <a class="btn-floating btn-large waves-effect waves-light red right modal-trigger" href="#addRepoModal">
            <i class="material-icons">add</i>
        </a>
    </div>
{% endblock %}